In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv(".//CSV//titanic.csv")
df.shape

(891, 12)

In [2]:
numerical_cols = df.select_dtypes(
    include=['int64','float64']
).columns

numerical_cols

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='str')

In [3]:
Q1 = df['Fare'].quantile(0.25)

Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR

upper = Q3 + 1.5 * IQR

outliers = df[
    (df['Fare'] < lower) |
    (df['Fare'] > upper)
]

print("Outliers:", len(outliers))

Outliers: 116

In [4]:
def detect_outliers_iqr(df, column):

    Q1 = df[column].quantile(0.25)

    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR

    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower) |
        (df[column] > upper)
    ]

    return len(outliers)

In [5]:
detect_outliers_iqr(df, 'Fare')

116

In [6]:
outlier_report = {}

for col in numerical_cols:

    outlier_report[col] = detect_outliers_iqr(
        df,
        col
    )

outlier_report

{'PassengerId': 0,
 'Survived': 0,
 'Pclass': 0,
 'Age': 11,
 'SibSp': 46,
 'Parch': 213,
 'Fare': 116}

In [7]:
outlier_df = pd.DataFrame(
    outlier_report.items(),
    columns=[
        "Column",
        "Outlier Count"
    ]
)

outlier_df

        Column  Outlier Count
0  PassengerId              0
1     Survived              0
2       Pclass              0
3          Age             11
4        SibSp             46
5        Parch            213
6         Fare            116

In [8]:
outlier_df[
    outlier_df["Outlier Count"] > 0
]

  Column  Outlier Count
3    Age             11
4  SibSp             46
5  Parch            213
6   Fare            116

In [9]:
def generate_outlier_report(df):

    numerical_cols = df.select_dtypes(
        include=['int64','float64']
    ).columns

    report = {}

    for col in numerical_cols:

        report[col] = detect_outliers_iqr(
            df,
            col
        )

    return pd.DataFrame(
        report.items(),
        columns=[
            "Column",
            "Outlier Count"
        ]
    )

In [10]:
generate_outlier_report(df)

        Column  Outlier Count
0  PassengerId              0
1     Survived              0
2       Pclass              0
3          Age             11
4        SibSp             46
5        Parch            213
6         Fare            116